export const BENCHMARK_PLATFORM_PATTERNS = [
  {
    key: 'cckp',
    label: 'World Bank Climate Change Knowledge Portal',
    shortLabel: 'WB CCKP',
    href: 'https://climateknowledgeportal.worldbank.org/',
    category: '국가 프로필 · 데이터 허브',
    pattern: '국가 프로필형 요약 + 국가/서브내셔널 탐색 + 다운로드 허브',
    borrowed: ['국가 프로필형 첫 화면', '서브내셔널 탐색 진입점', '다운로드 가능한 공개 데이터 흐름'],
    apply: '후보를 열면 먼저 국가·기술·근거를 한 줄로 압축하고, 바로 공식 문서·데이터 허브로 넘어가게 구성했습니다.',
    relevance: '국가 하나를 빠르게 훑고 회의 전 사실관계를 정리하는 흐름에 적합합니다.',
  },
  {
    key: 'data360',
    label: 'World Bank Data360',
    shortLabel: 'Data360',
    href: 'https://data360.worldbank.org/en/about',
    category: '원스톱 데이터 탐색',
    pattern: 'one-stop-shop 데이터 탐색 구조',
    borrowed: ['데이터 허브형 진입', '탐색 비용이 낮은 정보 구조', '출처 문서화'],
    apply: '실시간 지표, 공식 포털, 프로젝트 신호를 한 화면에서 이어 보도록 데이터 접근 동선을 줄였습니다.',
    relevance: '국가·기술·재원 검토에 필요한 링크를 여러 사이트로 튕기지 않고 한 흐름 안에서 정리하는 데 유효합니다.',
  },
  {
    key: 'ndgain',
    label: 'ND-GAIN Country Index',
    shortLabel: 'ND-GAIN',
    href: 'https://gain.nd.edu/our-work/country-index/',
    category: '리스크 · 준비도',
    pattern: '리스크·준비도·방법론 공개',
    borrowed: ['readiness/risk 비교', '점수 해석 가능성', '방법론 공개'],
    apply: '점수만 보여주지 않고 기회·준비도·리스크·실행성 밴드와 방법론 설명을 같이 배치했습니다.',
    relevance: '추천 결과를 “보기 좋은 점수”가 아니라 설명 가능한 판단으로 바꾸는 데 도움이 됩니다.',
  },
  {
    key: 'thinkhazard',
    label: 'ThinkHazard!',
    shortLabel: 'ThinkHazard!',
    href: 'https://thinkhazard.org/',
    category: '위치 기반 스크리닝',
    pattern: '위치 기반 위험 정보 + 바로 실행할 권고 문장',
    borrowed: ['위치 중심 판단', 'action-oriented 문장', '비전문가 친화적 진입'],
    apply: '지도·경계 검증과 다음 액션 문장을 함께 보여 실무자가 바로 설명할 수 있게 바꿨습니다.',
    relevance: '실증 후보지·위험지역 검토를 할 때 지도 결과를 바로 회의 언어로 번역하는 데 적합합니다.',
  },
  {
    key: 'gcf',
    label: 'GCF Open Data Library',
    shortLabel: 'GCF ODL',
    href: 'https://data.greenclimate.fund/',
    category: '프로젝트 · 재원 허브',
    pattern: '국가-프로젝트-재원 연결 구조',
    borrowed: ['국가-프로젝트 연결', '재원 탐색', 'Country/Projects/Readiness 분리'],
    apply: '프로젝트·재원 파이프라인, 국가 포털, 파트너 신호를 같은 검토 흐름에 묶었습니다.',
    relevance: 'ODA, readiness, 실증사업 검토에서 바로 재원 신호를 확인하는 데 유리합니다.',
  },
  {
    key: 'climatewatch',
    label: 'Climate Watch',
    shortLabel: 'Climate Watch',
    href: 'https://www.climatewatchdata.org/compare-all-targets',
    category: '국가 비교 · 다운로드',
    pattern: '비교형 탐색 + 다운로드 가능한 비교 구조',
    borrowed: ['side-by-side 비교', '문서 유형 비교', '데이터 내보내기'],
    apply: '보관 후보를 기준으로 side-by-side 비교 표와 CSV 추출을 추가했습니다.',
    relevance: '후보국 2~4개를 압축해 회의 안건화하거나 상사 보고용 비교표를 만드는 데 맞습니다.',
  },
  {
    key: 'ttclear',
    label: 'UNFCCC TT:CLEAR',
    shortLabel: 'TT:CLEAR',
    href: 'https://unfccc.int/ttclear/',
    category: '기술정책 · TNA 문서 허브',
    pattern: '기술정책·TNA·문서 허브',
    borrowed: ['기후기술 문서 허브', 'TNA/TAP 탐색', '기술 메커니즘 연결'],
    apply: '공식 문서 허브에서 정책·TNA·포털 링크를 역할별로 나눠 보이게 정리했습니다.',
    relevance: '기술협력 기획에서 “왜 이 기술인지”를 국제 제도와 연결해 설명할 때 유용합니다.',
  },
  {
    key: 'atlas',
    label: 'Global Solar/Wind Atlas · IRENA Global Atlas',
    shortLabel: 'Global Atlas',
    href: 'https://globalatlas.irena.org/',
    category: '지도 레이어 · 자원 탐색',
    pattern: '레이어 토글 + 지도 다운로드/공유 관점',
    borrowed: ['레이어 중심 탐색', '공간정보 기반 해석', '지도-다운로드 연결'],
    apply: '지도는 예쁜 배경이 아니라 판단용 레이어로 보이도록 focus 전환과 범례 구조를 유지·보강했습니다.',
    relevance: '재생에너지, 자원 잠재량, 후보지역 검토처럼 공간 근거가 핵심일 때 참고 가치가 큽니다.',
  },
];

export const BENCHMARK_IMPLEMENTATION_PRIORITIES = [
  '국가 프로필형 요약을 먼저 보여주고 상세 탭으로 내려가는 흐름',
  '추천과 검증된 사실을 구분하는 evidence block',
  '보관 후보 기반 비교표와 공유/다운로드 동선',
  '실시간 데이터와 fallback 상태를 한 번에 읽을 수 있는 상태판',
  '공식 문서 허브와 지도 탐색을 같은 업무 흐름에 묶는 구조',
];

export const BENCHMARK_RESOURCE_LINKS = [
  { key: 'cckp-explore', group: 'WB CCKP', label: 'Country & Subnational Explore', href: 'https://climateknowledgeportal.worldbank.org/explore' },
  { key: 'cckp-country-profiles', group: 'WB CCKP', label: 'Climate Risk Country Profiles', href: 'https://climateknowledgeportal.worldbank.org/country-profiles' },
  { key: 'cckp-download', group: 'WB CCKP', label: 'Download Data', href: 'https://climateknowledgeportal.worldbank.org/download-data' },
  { key: 'data360-about', group: 'Data360', label: 'About Data360', href: 'https://data360.worldbank.org/en/about' },
  { key: 'climatewatch-compare', group: 'Climate Watch', label: 'Compare all targets', href: 'https://www.climatewatchdata.org/compare-all-targets' },
  { key: 'climatewatch-custom-compare', group: 'Climate Watch', label: 'Custom compare', href: 'https://www.climatewatchdata.org/custom-compare' },
  { key: 'gcf-countries', group: 'GCF ODL', label: 'Countries database', href: 'https://data.greenclimate.fund/public/data/countries' },
  { key: 'gcf-projects', group: 'GCF ODL', label: 'Funded activities', href: 'https://data.greenclimate.fund/public/data/projects' },
  { key: 'gcf-readiness', group: 'GCF ODL', label: 'Readiness database', href: 'https://data.greenclimate.fund/public/data/readiness' },
  { key: 'ttclear-about', group: 'TT:CLEAR', label: 'About TT:CLEAR', href: 'https://unfccc.int/ttclear/about' },
  { key: 'ttclear-negotiations', group: 'TT:CLEAR', label: 'Technology negotiations', href: 'https://unfccc.int/ttclear/negotiations' },
  { key: 'thinkhazard-faq', group: 'ThinkHazard!', label: 'FAQ & interpretation limits', href: 'https://thinkhazard.org/en/faq' },
  { key: 'irena-global-atlas', group: 'Global Atlas', label: 'IRENA Global Atlas overview', href: 'https://www.irena.org/Energy-Transition/Project-Facilitation/Renewable-potential-assessment/Global-Atlas' },
];
